### ISSUE TITLE
Add general procyclic stage

### ISSUE THREAD

**Issue by Achchuthan** [OPL-ontology/OPL#10]
Label: trypanosomatida procyclic stage
Definition: A parasite lifecycle stage of trypanosomatidae in which the organism is in dividing form and it occurs in fly vector.
Parent class: 'parasite life cycle stage'
Children class: 'procyclic promastigote stage, 'procyclic trypomastigote stage'

**Comment by zhengj2007** [comment]
Current 'procyclic promastigote stage' is asserted as child of 'promastigote stage' and 'procyclic trypomastigote stage' is asserted as child of 'trypomastigote stage'. 

Is any realizable entity (role, disposition, quality) or sub-process or any entity can make 'trypanosomatida procyclic stage' different from other life cycle stage like what we defined 'Trypanosomatida metacyclic stage' using equivalent axiom?  @cstoeckert

**Comment by cstoeckert** [comment]
The defining characteristic of a procyclic stage appears to be they are dividing. @Achchuthan do you agree?
Maybe the equivalent class can be:
parasite lifecycle stage and (has part some cell division (http://purl.obolibrary.org/obo/GO_0051301) and has participant only trypanosomatida)

**Comment by cstoeckert** [comment]
May also need to specify the stage occurs in the fly (sand fly or tsetse fly) midgut.
https://www.cdc.gov/parasites/sleepingsickness/biology.html
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2839921/

**Comment by Achchuthan** [comment]
Hi @cstoeckert ,
I agree with you that the defining characteristic is that it is dividing. In addition, its presence in the fly vector.
Thanks,
Achchuthan

**Comment by zhengj2007** [comment]
Added and available in the latest release
