### ISSUE TITLE
New term request: bradyzoite stage

### ISSUE THREAD

**Issue by paolaroncaglia** [OPL-ontology/OPL#19]
Dear OPL developers (@cthoyt ?),

Would you please consider adding a new OPL term for 'bradyzoite stage':
Subclass of OPL:0000181 'parasite lifecycle stage'
Possible definition: "The life stage found in the tissue cyst which replicates slowly within a parasitophorous vacuole within the host cell." 
Synonyms: bradyzoite, cystozoite. 
Source: https://www.sciencedirect.com/topics/biochemistry-genetics-and-molecular-biology/tachyzoite

This request stems from a Cell Ontology (CL) ticket, https://github.com/obophenotype/cell-ontology/issues/270.
Would you prefer me to enter the information in a template as suggested in https://github.com/OPL-ontology/OPL?

Thank you,

Paola Roncaglia (CL and Uberon editorial team)

**Comment by zhengj2007** [comment]
Hi @paolaroncaglia, Please go ahead to add the new term in the template: https://github.com/OPL-ontology/OPL/blob/master/src/ontology/templates/opl_development_stage.tsv, create the pull request and assign me to review.

**Comment by paolaroncaglia** [comment]
@zhengj2007 Thank you for the super-prompt reply!
I used OPL:000324 as that seemed to be the next available ID, let me know otherwise. 
Also, there isn't a field for synonyms or references in the template, so I assume they're optional. Thank you again.

**Comment by zhengj2007** [comment]
Sounds good. I will generate the module based on the template. 

When do you want us to make the release? Do you have  any other new term request soon?

**Comment by paolaroncaglia** [comment]
@zhengj2007 

> Sounds good. I will generate the module based on the template.
> 
> When do you want us to make the release? Do you have any other new term request soon?

As far as I'm aware and based on searching the issue trackers, the Cell Ontology (or the Uberon anatomy ontology) don't need other OPL terms at the moment. We also don't need the terms to be released urgently, so it's up to you - feel free to make the release when it's more convenient for you. Thank you!

**Comment by zhengj2007** [comment]
Term is added
