### ISSUE TITLE
Plasmodium OPL terms

### ISSUE THREAD

**Issue by uliboehme** [OPL-ontology/OPL#2]
As discussed via e-mail please find attached the Plasmodium OPL terms. Definitions are the same as for P. falciparum terms. It would be great if you could deprecate the P. falciparum terms and replace them with Plasmodium terms. 
[OPL_defintion_Plasmodium.docx](https://github.com/OPL-ontology/OPL/files/3126067/OPL_defintion_Plasmodium.docx)

**Comment by cstoeckert** [comment]
Thank you for providing these terms. We will work on incorporating them.

**Comment by zhengj2007** [comment]
Hi @uliboehme, Thanks for submitting the new terms. I went through the terms, edited the definitions following OBO Foundry ontology development principles and added the Plasmodium lifecycle specific organism location information. Besides, for adding the terms you request, we need to add the corresponding lifecycle stage terms in the OPL too. So, I made the lifecycle stage terms with definitions. Could you please review whether the term labels, definitions and other information are correct before I add them in the OPL? Especially two terms highlighted in yellow that I have no idea about their difference.
Thanks!
[OPL_NTRs.xlsx](https://github.com/OPL-ontology/OPL/files/3163984/OPL_NTRs.xlsx)

**Comment by uliboehme** [comment]
Hi @zhengj2007, Thanks for going through the terms and editing the definitions. This looks good to me.  Regarding the two terms highlighted in yellow, if possible I would use the same definition as for sporozoite stage (A sporozoite stage in the Plasmodium lifecycle that occurs in the salivary glands of the mosquito and invades hepatocytes in the vertebrate host). Hope this is ok.

**Comment by zhengj2007** [comment]
Hi @uliboehme, Thanks for reviewing the terms. For ontology term, we need to have different definitions for different ontology terms. Otherwise, it doesn't make sense to create two terms. I will seek the help in our EuPathDB group and add the terms in OPL as soon as possible.

**Comment by zhengj2007** [comment]
Hi @uliboehme, I have added the terms you requested in the OPL. The labels and IDs are shown as follow:
| ID | Label |
| ----------- | ----------- |
| OPL_0000264 | Plasmodium gamete |
| OPL_0000265 | Plasmodium macrogamete |
| OPL_0000266 | Plasmodium microgamete |
| OPL_0000267 | Plasmodium gametocyte |
| OPL_0000268 | Plasmodium macrogametocyte |
| OPL_0000269 | Plasmodium microgametocyte |
| OPL_0000270 | Plasmodium merozoite |
| OPL_0000271 | Plasmodium erythrocytic merozoite |
| OPL_0000272 | Plasmodium hepatic merozoite |
| OPL_0000273 | Plasmodium oocyst |
| OPL_0000274 | Plasmodium ookinete |
| OPL_0000275 | Plasmodium schizont |
| OPL_0000276 | Plasmodium erythrocytic schizont |
| OPL_0000277 | Plasmodium hepatic schizont |
| OPL_0000278 | Plasmodium sporozoite |
| OPL_0000279 | Plasmodium oocyst-derived sporozoite |
| OPL_0000280 | Plasmodium salivary gland-derived sporozoite |
| OPL_0000281 | Plasmodium trophozoite |
| OPL_0000282 | Plasmodium erythrocytic trophozoite |
| OPL_0000283 | Plasmodium erythrocytic ring trophozoite |
| OPL_0000284 | Plasmodium hepatic trophozoite |
| OPL_0000285 | Plasmodium zygote |

Is it all you need? Do you need the new OPL release for you to use OWL file?
