### ISSUE TITLE
New parasite IDs for incorporation to VO.

### ISSUE THREAD

**Issue by Huffmaar** [OPL-ontology/OPL#21]
Hey All,
The VO team is interested in expanding VO to include some new life stage terms for parasite vaccines using OPL.
 The following species are ones we are interested in generating new terms for life stages (as occurent or material entity) for:

<html><body>

| Babesia bovis; Babesia canis
| Cryptosporidium parvum
| Eimeria acervulina; Eimeria maxima; Eimeria spp.; Eimeria tenella
| Entamoeba histolytica
| Giardia duodenalis 
| Leishmania amazonensis; Leishmania donovani; Leishmania infantum; 
| Neospora caninum; 
| Plasmodium gondii; Plasmodium knowlesi; Plasmodium ovale; Plasmodium vivax
| Sarcocystis neurona
| Schistosoma mansoni 
| Theileria annulata; Theileria parva
| Toxoplasma gondii
| Trichinella spiralis
| Trichomonas foetus

</body>
</html>

**Comment by zhengj2007** [comment]
Thanks for submitting NTRs. We'd like to add the terms when you provide the detailed developmental stage information.

**Comment by Huffmaar** [comment]
Here are the named developmental stage information. Do you also want a definition for each of these terms for submission?
P. vivax ookinetes; sporozoite; merozoite; gametocyte
P. berghei sporazoite; meorzoite
N. canium tachyzoite
E. maxima gametocyte
E. tenella sprozoite; oocyst
S. neurona merozoite; sporozoite
T. gondii tachyzoite; bradyzoite; oocysts
T. cruzi trypomastigote; amastigote; epimastigote
L. amazonesis asmotigote; promastigote
L. donovani promastigote; amastigote
L. infantum promastigote; amastigote
L. major promastigote; amastigote

**Comment by zhengj2007** [comment]
Do you also have host, vector, or where the lifecycle stage occurs information? @Huffmaar

**Comment by Huffmaar** [comment]
Will this be sufficient?
merozoites and gametocytes occur in host bloodstream; amastigotes  within infected tissue and bloodstream; sporocytes, promastigotes, and ookinetes in vector gut. 
P. vivax ookinetes; sporozoite; merozoite; gametocyte.   Host: Human Vector: Anopholes genus
P. berghei sporozoite; merozoite Host: Human Vector: Anopholes genus
N. canium tachyzoite  Host: Canids (genus Canis)
E. maxima gametocyte Host: Chicken
E. tenella sporozoite; oocyst Host: Chicken
S. neurona merozoite; sporozoite Host: Dog 
T. gondii tachyzoite; bradyzoite; oocysts Host: Human Vector: Triatomine Bug (Triatominae subfamily)
T. cruzi trypomastigote; amastigote; epimastigote Host: Human Vector: Triatomine Bug (Triatominae subfamily)
L. amazonesis asmotigote; promastigote Host: Human Vector: Sandfly (Lutzomyia genus)
L. donovani promastigote; amastigote Host: Human Vector: Sandfly (Lutzomyia genus)
L. infantum promastigote; amastigote Host: Human Vector: Sandfly (Lutzomyia genus, Lutzomyia longipalpis)
L. major promastigote; amastigote Host: Human Vector: Sandfly (Lutzomyia genus)

**Comment by zhengj2007** [comment]
Following terms are already in OPL:
T. cruzi trypomastigote; amastigote; epimastigote Host: Human Vector: Triatomine Bug (Triatominae subfamily)
L. major promastigote; amastigote Host: Human Vector: Sandfly (Lutzomyia genus)

**Comment by zhengj2007** [comment]
By checking online, changed host of some parasites:
P. vivax: Host: Human -> Vertebrata
P. berghei: Host: Human -> Mammalia
T. gondii: Host: Human -> Mammalia
L. amazonesis: Host: Human -> Mammalia
L. infantum: Host: Human -> Mammalia

**Comment by zhengj2007** [comment]
@Huffmaar Could you please provide the definition of "tachyzoite stage". So far, it is the only thing I need for adding the terms you needed. Thanks!

**Comment by Huffmaar** [comment]
Tachyzoite stage: "Tachyzoites (tachos = fast) refer to the rapidly growing life stage of T. gondii that has also been called endozoites or trophozoites. " -- https://www.sciencedirect.com/topics/immunology-and-microbiology/tachyzoite

**Comment by zhengj2007** [comment]
The terms were added in https://github.com/OPL-ontology/OPL/pull/22
