### ISSUE TITLE
Additional OPL Terms

### ISSUE THREAD

**Issue by Huffmaar** [OPL-ontology/OPL#24]
I request the following terms be added to OPL (both as a parasite and with a corresponding life stage):

Plasmodium yoleii:  Vector - Anopholes, Host - Primates
Plasmodium yoleii ookinetes
Plasmodium yoleii sporozoite
Plasmodium yoleii merozoite
Plasmodium yoleii gametocyte

Plasmodium chabaudi: Vector - Anopholes, Host - Primates
Plasmodium chabaudi ookinetes
Plasmodium chabaudi sporozoite
Plasmodium chabaudi merozoite
Plasmodium chabaudi gametocyte

Plasmodium knowlesi: Vector - Anopholes, Host - Primates
Plasmodium knowlesi ookinetes
Plasmodium knowlesi sporozoite
Plasmodium knowlesi merozoite
Plasmodium knowlesi gametocyte
-- Plasmoidum lifecycle reference: [https://www.cdc.gov/dpdx/malaria/index.html]

Neospora caninum: Host: Canid, Cow
Neospora caninum tachyocyte: occurs in cattle tissue
--Neospora lifecycle reference: [https://www.mdpi.com/2306-7381/9/2/87]

Eimeria acervulina: Host: Chicken
Eimeria acervulina merozoite: occurs in Chicken tissue
Eimeria maxima gametocyte: occurs in Chicken gut
--Eimeria reference: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7351014/

Cryptosporidium  parvum: Host: Mammal 
Cryptosporidium  parvum oocyst
Cryptosporidium  parvum sporozoite
-- Cryptosporidium reference: https://www.cdc.gov/parasites/crypto/pathogen.html

Using Issue #16.
Merozoites and gametocytes occur in host bloodstream; 
Sporocytes, promastigotes, and ookinetes occur in vector gut.

**Comment by zhengj2007** [comment]
Corrected typo:

Plasmodium yoelii:  Vector - Anopholes, Host - Primates
Plasmodium yoelii ookinetes
Plasmodium yoelii sporozoite
Plasmodium yoelii merozoite
Plasmodium yoelii gametocyte

**Comment by zhengj2007** [comment]
> Neospora caninum: Host: Canid, Cow
Neospora caninum tachyocyte: occurs in cattle tissue
--Neospora lifecycle reference: [https://www.mdpi.com/2306-7381/9/2/87]

Is it typo? The lifecycle [Neospora caninum tachyzoite](http://purl.obolibrary.org/obo/OPL_0000332) has been added. Please check any information need to be updated. The one added only indicate host, 'Canis'.

**Comment by zhengj2007** [comment]
Eimeria maxima gametocyte: occurs in Chicken gut already in OPL.
http://purl.obolibrary.org/obo/OPL_0000333

**Comment by Huffmaar** [comment]
For the three comments:
Pladomoidum yoleii typo correction is appreciated.
Neospora canine tachyocyte should bradyzoite
Eimeria maxima gametocyte was listed with OPL_0000333 (which I thought was not added until before).

**Comment by zhengj2007** [comment]
Added requested terms:

OPL ID | Label
-- | --
OPL:0000384 | Plasmodium yoelii ookinete
OPL:0000385 | Plasmodium yoelii sporozoite
OPL:0000386 | Plasmodium yoelii merozoite
OPL:0000387 | Plasmodium yoelii gametocyte
OPL:0000388 | Plasmodium chabaudi ookinete
OPL:0000389 | Plasmodium chabaudi sporozoite
OPL:0000390 | Plasmodium chabaudi merozoite
OPL:0000391 | Plasmodium chabaudi gametocyte
OPL:0000392 | Plasmodium knowlesi ookinete
OPL:0000393 | Plasmodium knowlesi sporozoite
OPL:0000394 | Plasmodium knowlesi merozoite
OPL:0000395 | Plasmodium knowlesi gametocyte
OPL:0000396 | Eimeria acervulina merozoite
OPL:0000397 | Cryptosporidium parvum oocyst
OPL:0000398 | Cryptosporidium parvum sporozoite
OPL:0000420 | Neospora caninum bradyzoite
