### ISSUE TITLE
IDOMAL organism terms

### ISSUE THREAD

**Issue by zhengj2007** [OPL-ontology/OPL#3]
We used a couple of IDOMAL terms in OPL that are also available in NCBITaxon.

Shall we replace mammal: IDOMAL_0000605 by Mammalia: NCBITaxon_40674 and vertebrate: IDOMAL_0001274 by Vertebrata <Metazoa>: NCBITaxon_7742?

**Comment by zhengj2007** [comment]
Found one more IDOMAL organism term that is available in NCBITaxon.
Shall replace insect: IDOMAL_0000565 by Insecta: NCBITaxon_50557?

**Comment by cstoeckert** [comment]
+1 to replacing IDOMAL terms with NCBITaxon. That will provide greater consistency with other ontologies especially as IDOMAL is no longer developed.
