### ISSUE TITLE
Create opl-base

### ISSUE THREAD

**Issue by cmungall** [OPL-ontology/OPL#7]
We would like a base file so we can include opl in the go import chain. See https://github.com/geneontology/go-ontology/issues/17941#issuecomment-537898963

**Comment by cstoeckert** [comment]
@cmungall Can you expand on what exactly we need to provide from OPL? Happy to do this but just not clear what opl-base means. Thanks.

**Comment by zhengj2007** [comment]
Hi @cmungall, I aligned OPL with other stage ontologies and created the release candidate, and opl-base,
https://github.com/OPL-ontology/OPL/blob/opl-base/opl_base.owl

Could you please review whether it is what you need? Thanks!
