### ISSUE TITLE
Align datamodel for OPL with other stage ontologies

### ISSUE THREAD

**Issue by cmungall** [OPL-ontology/OPL#8]
The @bgeedb team have made a repo with 20 stage ontologies https://github.com/obophenotype/developmental-stage-ontologies

It would be good to align the DPs in OPL with this and with Uberon. We will need this for import into GO. For example, for taxon constraints we assume in_taxon rather than has_participant

**Comment by cstoeckert** [comment]
We will update and compare our current pattern to Uberon but parasites have restrictions based on host that may not make it possible to completely match.

**Comment by zhengj2007** [comment]
[OPL design patterns](https://github.com/OPL-ontology/OPL/blob/master/doc/template/OPL_patterns.jpg)

1. OPL does not contain relations between different developmental stages. Consider to add timing Relations in OPL

- temporal ordering relations
	- http://purl.obolibrary.org/obo/BFO_0000062 preceded by
	(inverse relation: http://purl.obolibrary.org/obo/BFO_0000063 precedes)
	- http://purl.obolibrary.org/obo/RO_0002087 immediately preceded by (starts at end of)
	(inverse relation: http://purl.obolibrary.org/obo/RO_0002090 immediately precedes)

- part relation
	- http://purl.obolibrary.org/obo/BFO_0000050 part_of 
	to connect sub-stages to stages that temporally contain them
	(inverse relation: http://purl.obolibrary.org/obo/BFO_0000051 has part)

	It may solve the issue that some sub-stages part of same stage occur in different organisms / locations.

	Notes: I think we should not apply part relations to organism at different specific stages. 

- includes numeric timing information using OWL datatypes (e.g. has_day 23^^xsd:int)
	For example, http://purl.obolibrary.org/obo/OPL_0000046 Schistosoma japonicum 6 day schistosomulum stage, need to provide logical axioms and specify the time using OWL datatypes.

2. Relation between organism developmental stage and organism
- obophenotype: http://purl.obolibrary.org/obo/RO_0002160 'only in taxon'
	(HSAPDV - Human Developmental Stages)	

- OPL: http://purl.obolibrary.org/obo/RO_0000057 'has participant'

Keep what we used for inferred hierarchy we need now. May consider to replace it if other stage ontologies all use 'only in taxon' relation.

**Comment by zhengj2007** [comment]
It seems only_in_taxon is usually used in relate developmental stage to organism. The relation is available in RO:
http://purl.obolibrary.org/obo/RO_0002160 

Will replace 'has_participant' with only_in_taxon in OPL

**Comment by zhengj2007** [comment]
Hi @cmungall, I have replaced taxon constraints has_participant with only_in_taxon for aligning with other stage ontology data model. Could you please review whether it is good for GO to import?

**Comment by zhengj2007** [comment]
Since only_in_taxon is deprecated, 'in taxon' relation is used to associate developmental stage with organism.
