### ISSUE TITLE
Add general metacyclic stage

### ISSUE THREAD

**Issue by cstoeckert** [OPL-ontology/OPL#9]
Request came up in context of https://github.com/geneontology/go-ontology/issues/17941

**Comment by cstoeckert** [comment]
Label:  trypanosomatida metacyclic stage
Definition: A parasite lifecycle stage of trypanosomatidae in which the organism is infectious and does not multiply. 
Definition source: https://microbewiki.kenyon.edu/index.php/Trypanosome_Life_Cycle, https://web.stanford.edu/group/parasites/ParaSites2003/Leishmania/Leish%20Biology.html
Parent class: 'parasite life cycle stage'

**Comment by Achchuthan** [comment]
Hi @cstoeckert.
Thanks a lot for working on the definition. I am happy with it.
Best wishes,
Achchuthan

**Comment by cstoeckert** [comment]
For a logical definition matching the textual definition, how about:
Equivalent:
'parasite life cycle stage' and (has participant only trypanosomatidae and realizes some 'infectious agent role') 

We would then add to http://purl.obolibrary.org/obo/OPL_0000006  and http://purl.obolibrary.org/obo/OPL_0000149:
Subclass:
has participant only trypanosomatidae and realizes some 'infectious agent role'

@zhengj2007 do you think this will work?

Note will need to import http://purl.obolibrary.org/obo/NCBITaxon_5654 into OPL and place Leishmania and Trypanosoma under it. Also need to import http://purl.obolibrary.org/obo/IDO_0000404.

**Comment by zhengj2007** [comment]
@cstoeckert Is 'metacyclic stage' the only stage in trypanosomatidae lifecycle that can realizes 'infectious agent role'? If so, it would work.

**Comment by cstoeckert** [comment]
That is my understanding. @Achchuthan can you confirm? Thanks.

**Comment by zhengj2007** [comment]
I found we have following terms in OPL:
metacyclic trypomastigote stage http://purl.obolibrary.org/obo/OPL_0000149
subClassOf 'trypomastigote stage' (http://purl.obolibrary.org/obo/OPL_0000033)
and
metacyclic promastigote stage http://purl.obolibrary.org/obo/OPL_0000006
subClassOf 'promastigote stage' (http://purl.obolibrary.org/obo/OPL_0000151)

Should 'metacyclic trypomastigote stage' and 'metacyclic promastigote stage' also be subClassOf 'trypanosomatida metacyclic stage'?
Besides, these two stages should also only be lifecycle stage of trypanosomatida and realize 'infectious agent role'. Am I right? @cstoeckert @Achchuthan

**Comment by Achchuthan** [comment]
Hi @zhengj2007,
I agree with you.
Thanks,
Achchuthan

**Comment by zhengj2007** [comment]
Added ‘Trypanosomatida metacyclic stage’ in OPL. The ID is OPL_0000322 with alternative label, 'metacyclic stage’.

**Comment by zhengj2007** [comment]
Added and available in the latest release
